language: python
python:
        - "2.7"

script: nosetests -v

before_install:
        - sudo apt-get update
        - sudo apt-get install python-opencv

notifications:
        email:
                on_success: never
                on_failure: always

