language: python
python:
        - "2.7"

script: nosetests -v

virtualenv:
        system_site_packages: true

before_install:
        - sudo apt-get install -qq python-opencv

notifications:
        email:
                on_success: never
                on_failure: always

